# Generated by Django 2.1 on 2020-05-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like_click',
            field=models.IntegerField(default=0, verbose_name='点赞次数'),
        ),
    ]
