# Generated by Django 2.1 on 2020-07-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_like_click'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='友链url')),
                ('name', models.CharField(max_length=100, verbose_name='友链名称')),
            ],
            options={
                'verbose_name': '友链',
                'verbose_name_plural': '友链',
            },
        ),
    ]
